# Generated by Django 4.2.16 on 2024-09-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0019_profile_queue_alter_category_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='queue',
            field=models.BooleanField(default=True, verbose_name='Enable Queue'),
        ),
    ]
