# Generated by Django 4.2.16 on 2024-09-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0021_student_graduation_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='graduation_year',
            new_name='yog',
        ),
    ]
